- name: Dise침o gr치fico
  image: assets/img/services/graphical.jpg
  href: /services/design/
  cover: assets/img/services/cover.jpg
  position: left
  tags: 
    - tec: Photoshop
    - tec: Illustrador
    - tec: Camtasia
  description: |
    Sed egestas, ante et vulputate volutpat, eros pede semper est, vitae luctus metus
    libero eu augue. Morbi purus libero, faucibus adipiscing, commodo quis, gravida 
    id, est.Sed egestas, ante et vulputate volutpat, eros pede semper est, vitae luctus metus 
    libero eu augue. Morbi purus libero, faucibus adipiscing, commodo quis, gravida 
    id, est.

- name: Desarrollo de p치ginas web
  image: assets/img/services/web.jpg
  href: /services/web/
  cover: assets/img/services/cover.jpg
  position: right  
  tags: 
    - tec: Ruby on Rails
    - tec: Node js
    - tec: WordPress
    - tec: Laravel
    - tec: Jekyll
    - tec: React    
  description: |
    Sed egestas, ante et vulputate volutpat, eros pede semper est, vitae luctus metus 
    libero eu augue. Morbi purus libero, faucibus adipiscing, commodo quis, gravida 
    id, est.Sed egestas, ante et vulputate volutpat, eros pede semper est, vitae luctus metus 
    libero eu augue. Morbi purus libero, faucibus adipiscing, commodo quis, gravida 
    id, est.

- name: Desarrollo de Apps m칩viles
  image: assets/img/services/mobile.jpg
  href: /services/mobile/
  cover: assets/img/services/cover.jpg
  position: left
  tags: 
    - tec: Java
    - tec: React Native
    - tec: Kotlin
    - tec: Xamarin
  description: |
    Sed egestas, ante et vulputate volutpat, eros pede semper est, vitae luctus metus 
    libero eu augue. Morbi purus libero, faucibus adipiscing, commodo quis, gravida 
    id, est.Sed egestas, ante et vulputate volutpat, eros pede semper est, vitae luctus metus 
    libero eu augue. Morbi purus libero, faucibus adipiscing, commodo quis, gravida 
    id, est.

- name: Marketing digital
  image: assets/img/services/media.jpg
  href: /services/marketing/
  cover: assets/img/services/cover.jpg
  position: right
  tags: 
    - tec: Facebook
    - tec: Twitter
    - tec: Instagram
    - tec: Linkedin
  description: |
    Sed egestas, ante et vulputate volutpat, eros pede semper est, vitae luctus metus 
    libero eu augue. Morbi purus libero, faucibus adipiscing, commodo quis, gravida
    id, est.Sed egestas, ante et vulputate volutpat, eros pede semper est, vitae luctus metus 
    libero eu augue. Morbi purus libero, faucibus adipiscing, commodo quis, gravida 
    id, est.


